### ISSUE TITLE
System.ComponentModel.Win32Exception when minimized

### ISSUE THREAD

**Issue by IncPlusPlus** [IncPlusPlus/titanfall2-rp#79]
Apparently this will throw exceptions when the console window is minimized. No clue why. Here's what gets spammed.

```
System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetProcessHandle(Int32 access, Boolean throwIfExited)
   at System.Diagnostics.Process.GetOrOpenProcessHandle()
   at System.Diagnostics.Process.EnsureWatchingForExit()
   at System.Diagnostics.Process.set_EnableRaisingEvents(Boolean value)
   at Process.NET.ProcessSharp..ctor(Process native, MemoryType type)
   at titanfall2_rp.ProcessNetApi.Init()
   at titanfall2_rp.Titanfall2Api._ensureInit()
   at titanfall2_rp.Titanfall2Api.GetGameModeAndMapName()
   at titanfall2_rp.PresenceUpdateThread.GetDetailsAndState(Titanfall2Api tf2Api)
   at titanfall2_rp.PresenceUpdateThread.SetCurrentPresence(DiscordRpcClient client, Titanfall2Api tf2Api)
   at titanfall2_rp.PresenceUpdateThread.OnTimedEvent(Object source, ElapsedEventArgs e)
```

Log file:
[titanfall-rp (1).log](https://github.com/IncPlusPlus/titanfall2-rp/files/7148897/titanfall-rp.1.log)

**Comment by IncPlusPlus** [comment]
I've also learned from this log that I forgot Frontier Defense: Master lol

To be fixed with #80

**Comment by IncPlusPlus** [comment]
I've still been unable to replicate this.
